version: "3"
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        MYSQL_HOST: "${MYSQL_HOST}"
        MYSQL_DBNAME: "${MYSQL_DBNAME}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "8260:80"
    volumes:
      - .:/var/www/html
    container_name: swag_backoffice
    network_mode: "bridge"
    extra_hosts:
      - "host.docker.internal:host-gateway"

